jin_prof/urls.py
"""
URLマッピング定義ファイル

- 管理サイトページ
- profアプリケーションの各ページ
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path(settings.ADMIN_PATH, admin.site.urls),
    path('', include('prof.urls')),
]

prof/urls.py
"""
URLマッピング定義ファイル

- indexページ
- studyページ
"""
from django.urls import path

from prof import views


app_name = 'prof'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('study/', views.StudyView.as_view(), name='study'),
]

prof/models.py
"""
モデル定義ファイル

- Profileモデル
- Skillsモデル
- CareersListモデル
- Studyモデル
- Commentsモデル
"""
from django.db import models


class Profile(models.Model):
    """Profileモデルを定義"""
    home_address = models.CharField(max_length=20)
    careers_text = models.TextField()
    hobbies = models.TextField()

    def __str__(self):
        """
        管理画面のレコードを判別するためのタイトルを定義する

        Returns
        -------
        record_title: str
            管理画面のレコードを判別するためのタイトル
        """
        return 'jin'


class Skills(models.Model):
    """Skillsモデルを定義"""
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='skills',
    )
    skill = models.CharField(max_length=20)


class CareersList(models.Model):
    """CareersListモデルを定義"""
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='careers_list',
    )
    company = models.CharField(max_length=20)
    job = models.CharField(max_length=20)


class Study(models.Model):
    """Studyモデルを定義"""
    title = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        """
        管理画面のレコードを判別するためのタイトルを定義する

        Returns
        -------
        record_title: str
            管理画面のレコードを判別するためのタイトル
        """
        return self.title


class Comments(models.Model):
    """Commentsモデルを定義"""
    study = models.ForeignKey(
        Study,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    comment = models.TextField()
    created_at = models.DateField()

prof/views.py
"""
ビュー定義ファイル

- indexページ
- studyページ
"""
from django.db.models import Max
from django.views.generic import ListView

from prof.models import Profile
from prof.models import Study


class IndexView(ListView):
    """Profileモデルをリスト表示する処理を定義"""
    context_object_name = "profile_list"
    model = Profile
    template_name = 'prof/index.html'


class StudyView(ListView):
    """Studyモデルをリスト表示する処理を定義"""
    context_object_name = "study_list"
    queryset = Study.objects.annotate(
        latest_created_at=Max('comments__created_at'),
    ).order_by('-latest_created_at')
    template_name = 'prof/study.html'

prof/templates/prof/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div
  class="grid justify-items-center mb-14 space-y-6
    md:grid-cols-2 md:space-y-0">
  <div class="space-y-6 text-center">
    <img
      class="rounded-full w-64"
      src="{% static 'images/profile.png' %}"
      alt="profile image">

    <div class="font-bold">
      <h2 class="mb-3 text-3xl">
        Shogo Jinta
      </h2>
      <p>
        {{ profile_list.0.home_address }}
        在住
      </p>
      <p>
        1992年生まれ
      </p>
    </div>
  </div>

  <div class="space-y-14">
    <div class="space-y-3">
      <h2 class="font-bold text-3xl">
        Skills
      </h2>
      <p>
        {% for skills in profile_list.0.skills.all %}
          {{ skills.skill }}
          {% if not forloop.last %}
            /
          {% endif %}
        {% endfor %}
      </p>
    </div>

    <div>
      <h2 class="font-bold text-3xl mb-3">
        Careers
      </h2>
      <ol class="font-bold mb-10">
        {% for careers in profile_list.0.careers_list.all %}
          <li>
            {{ forloop.counter }}. {{ careers.company }}({{ careers.job }})
          </li>
        {% endfor %}
      </ol>
      <div class="space-y-5 leading-7">
        <p>
          {{ profile_list.0.careers_text|safe|linebreaksbr }}
        </p>
      </div>
    </div>

    <div class="space-y-3">
      <h2 class="font-bold text-3xl">
        Hobbies
      </h2>
      <div>
        <p>
          {{ profile_list.0.hobbies|linebreaks }}
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

prof/templates/prof/study.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
  <div class="flex items-center mb-10 space-x-5">
    <img
      class="w-40"
      src="{% static 'images/study.png' %}"
      alt="profile image">

    <h2 class="font-bold text-3xl">
      Study logs
    </h2>
  </div>

  <div class="space-y-8">
    {% for study in study_list %}
      <div class="border border-base p-5 rounded-lg shadow-md space-y-5">
        <h2 class="font-bold text-lg hover:opacity-80">
          <a
            href="{{ study.url }}"
            target="_blank">
            {{ study.title }}
          </a>
        </h2>
        {% for comments in study.comments.all %}
          <div class="space-y-1">
            <p class="opacity-80 text-xs">
              [{{ comments.created_at|date:"Y/m/d" }}]
            </p>
            <p>
              {{ comments.comment|linebreaks }}
            </p>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Shogo Jintaのプロフィールサイト。">

  <link rel="stylesheet" type="text/css" href="{% static 'css/dist.css' %}" />
  <link
    href="{% static 'fontawesomefree/css/fontawesome.css' %}"
    rel="stylesheet"
    type="text/css">
  <link
    href="{% static 'fontawesomefree/css/brands.css' %}"
    rel="stylesheet"
    type="text/css">
  <link
    href="{% static 'fontawesomefree/css/solid.css' %}"
    rel="stylesheet"
    type="text/css">
  <link rel="icon" href="{% static 'images/favicon.ico' %}">

  <title>Jin</title>

  {% if GOOGLE_ANALYTICS_TRACKING_ID %}
    {% include 'ga.html' %}
  {% endif %}
</head>
<body class="font-sans antialiased">
  {% block header %}
  <header class="sticky top-0 z-10">
    <div
      class="bg-base flex font-bold h-14 items-center
        justify-between px-10 text-white">
      <h1 class="text-2xl">
        Shogo Jinta
      </h1>

      <nav class="space-x-5 md:space-x-10">
        <a
          href="{% url 'prof:index' %}"
          class="space-x-1 hover:opacity-80">
          <span class="hidden sm:inline-block">
            Profile
          </span>
          <i class="fa-solid fa-address-card"></i>
        </a>

        <a
          href="{% url 'prof:study' %}"
          class="space-x-1 hover:opacity-80">
          <span class="hidden sm:inline-block">
            Study
          </span>
          <i class="fa-solid fa-book-open"></i>
        </a>

        <a
          class="space-x-1 hover:opacity-80"
          href="https://github.com/jin1125"
          target="_blank">
          <span class="hidden sm:inline-block">
            Github
          </span>
          <i class="fa-brands fa-github"></i>
        </a>
      </nav>
    </div>
  </header>
  {% endblock %}

  <main class="m-6 text-base md:m-12">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/base_error.html
{% extends 'base.html' %}

{% block content %}
<div class="font-bold pt-10 space-y-16 text-center">
  <h2 class="text-2xl">
    {% block error_message %}
    {% endblock %}
  </h2>

  <a
    href="{% url 'prof:index' %}"
    class="bg-base inline-block px-10 py-1 rounded-full text-white">
    Back
  </a>
</div>
{% endblock %}

templates/ga.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GSJGR2540P">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());

  gtag('config', 'G-GSJGR2540P');
</script>